name = "Cum Ranch"
author = "yuitaka"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b75b1118af7b60f1aa8cf93c6073384ce9f8cf24bb6200c22d5305546681eab"

[versions]
forge = "36.1.6"
minecraft = "1.16.5"
