name = "Daybreak"
author = "reo-ar"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ed3f9abcf11deb4a588940d91d0eb960476dbef1ca3a2b2b38d1db9b3d6a2cc"

[versions]
forge = "35.1.13"
minecraft = "1.16.4"
