name = "Cum Ranch"
author = "yuitaka"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f5ee84b6bd39e98c6211361f7142d9c369efafdafb6f58196ef98cfe089ced2"

[versions]
forge = "36.1.6"
minecraft = "1.16.5"
