name = "Daybreak"
author = "reo-ar"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "156123a230b65f141da6a7fb2559f46781da4453d5792b3cd10dc42f81af5aca"

[versions]
forge = "35.1.13"
minecraft = "1.16.4"
