name = "Cum Ranch"
author = "yuitaka"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf2bde67b002c8cbfe14e7fe98083ac75ae9ab07c1c206a39636f3465eeb7911"

[versions]
forge = "36.1.6"
minecraft = "1.16.5"
