name = "Daybreak"
author = "reo-ar"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3a13cd2f789b6b8507fff447cda2ff328c9d4adcbadf7473fc2ecacebf130a9"

[versions]
forge = "35.1.13"
minecraft = "1.16.4"
