name = "Cum Ranch"
author = "yuitaka"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d53bf192f91ba04a40619d4139d9c4c4f9aedaf0757608f2a142df97fa9f4aeb"

[versions]
forge = "36.1.6"
minecraft = "1.16.5"
