name = "Cum Ranch"
author = "yuitaka"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e076897c30b23cc2e3ffaf8a319a84c2a1864538b375719bc6672b040778eee1"

[versions]
forge = "36.1.6"
minecraft = "1.16.5"
