name = "Daybreak"
author = "reo-ar"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8601541baea61183c4653acde4125d1bdaf7e844441fd43afab7cbf28980b1a4"

[versions]
forge = "35.1.13"
minecraft = "1.16.4"
