name = "Cum Ranch"
author = "yuitaka"
version = "0.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40535b2bc07656c5cafd3f5f0b8af916aa220d3a610fec5bb156d562559fc98d"

[versions]
forge = "36.1.6"
minecraft = "1.16.5"
