name = "Advanced Mining Dimension"
filename = "mining_dimension-1.16.5-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3242/528/mining_dimension-1.16.5-1.0.4.jar"
hash-format = "murmur2"
hash = "800028799"

[update]
[update.curseforge]
file-id = 3242528
project-id = 332640
release-channel = "beta"
