name = "Advanced Chimneys"
filename = "AdChimneys-1.16.4-6.0.5.0-build.0032.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3161/174/AdChimneys-1.16.4-6.0.5.0-build.0032.jar"
hash-format = "murmur2"
hash = "2669635324"

[update]
[update.curseforge]
file-id = 3161174
project-id = 244830
release-channel = "beta"
