name = "AE2 Extras"
filename = "ae2extras-1.2-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3167/27/ae2extras-1.2-1.16.4.jar"
hash-format = "murmur2"
hash = "724803420"

[update]
[update.curseforge]
file-id = 3167027
project-id = 421104
release-channel = "beta"
