name = "AmbientSounds 3"
filename = "AmbientSounds_v3.1.4_mc1.16.4.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3140/456/AmbientSounds_v3.1.4_mc1.16.4.jar"
hash-format = "murmur2"
hash = "287765051"

[update]
[update.curseforge]
file-id = 3140456
project-id = 254284
release-channel = "beta"
