name = "Applied Energistics 2"
filename = "appliedenergistics2-8.2.0-beta.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3156/262/appliedenergistics2-8.2.0-beta.2.jar"
hash-format = "murmur2"
hash = "621106837"

[update]
[update.curseforge]
file-id = 3156262
project-id = 223794
release-channel = "beta"
