name = "Applied Energistics 2"
filename = "appliedenergistics2-8.2.0-alpha.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3118/473/appliedenergistics2-8.2.0-alpha.2.jar"
hash-format = "murmur2"
hash = "247763974"

[update]
[update.curseforge]
file-id = 3118473
project-id = 223794
release-channel = "beta"
