name = "Architectury API (Forge)"
filename = "architectury-1.12.145-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3279/826/architectury-1.12.145-forge.jar"
hash-format = "murmur2"
hash = "1429561189"

[update]
[update.curseforge]
file-id = 3279826
project-id = 419699
release-channel = "beta"
