name = "Architectury (Forge)"
filename = "architectury-1.3.78-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3166/478/architectury-1.3.78-forge.jar"
hash-format = "murmur2"
hash = "2601378875"

[update]
[update.curseforge]
file-id = 3166478
project-id = 419699
release-channel = "beta"
