name = "Ars Nouveau"
filename = "ars_nouveau-1.16.4-1.9.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3143/421/ars_nouveau-1.16.4-1.9.2.jar"
hash-format = "murmur2"
hash = "2773885070"

[update]
[update.curseforge]
file-id = 3143421
project-id = 401955
release-channel = "beta"
