name = "ATO - All the Ores"
filename = "alltheores-0.1.13-1.16.3-34.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3092/918/alltheores-0.1.13-1.16.3-34.1.0.jar"
hash-format = "murmur2"
hash = "163728768"

[update]
[update.curseforge]
file-id = 3092918
project-id = 405593
release-channel = "beta"
