name = "AttributeFix"
filename = "AttributeFix-1.16.4-9.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3112/152/AttributeFix-1.16.4-9.0.2.jar"
hash-format = "murmur2"
hash = "1866458742"

[update]
[update.curseforge]
file-id = 3112152
project-id = 280510
release-channel = "beta"
