name = "AutoRegLib"
filename = "AutoRegLib-1.6-47.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3128/555/AutoRegLib-1.6-47.jar"
hash-format = "murmur2"
hash = "2240982638"

[update]
[update.curseforge]
file-id = 3128555
project-id = 250363
release-channel = "beta"
