name = "Bad Wither No Cookie - Reloaded"
filename = "bwncr-1.16.4-3.9.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3101/531/bwncr-1.16.4-3.9.16.jar"
hash-format = "murmur2"
hash = "4149953045"

[update]
[update.curseforge]
file-id = 3101531
project-id = 261251
release-channel = "beta"
