name = "Better Advancements"
filename = "BetterAdvancements-1.16.4-0.1.0.103.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3109/976/BetterAdvancements-1.16.4-0.1.0.103.jar"
hash-format = "murmur2"
hash = "10261566"

[update]
[update.curseforge]
file-id = 3109976
project-id = 272515
release-channel = "beta"
