name = "Biomes O' Plenty"
filename = "BiomesOPlenty-1.16.5-13.1.0.457-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3288/5/BiomesOPlenty-1.16.5-13.1.0.457-universal.jar"
hash-format = "murmur2"
hash = "2571388601"

[update]
[update.curseforge]
file-id = 3288005
project-id = 220318
release-channel = "beta"
