name = "Blame (Forge)"
filename = "blame-1.7.5.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3145/310/blame-1.7.5.jar"
hash-format = "murmur2"
hash = "3390800573"

[update]
[update.curseforge]
file-id = 3145310
project-id = 406201
release-channel = "beta"
