name = "Blame (Forge)"
filename = "blame-1.16.4-1.9.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3181/314/blame-1.16.4-1.9.2.jar"
hash-format = "murmur2"
hash = "454221230"

[update]
[update.curseforge]
file-id = 3181314
project-id = 406201
release-channel = "beta"
