name = "Blame (Forge)"
filename = "blame-1.7.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3135/54/blame-1.7.4.jar"
hash-format = "murmur2"
hash = "2929620867"

[update]
[update.curseforge]
file-id = 3135054
project-id = 406201
release-channel = "beta"
