name = "Blood Magic "
filename = "BloodMagic-1.16.4-3.1.0-15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3184/485/BloodMagic-1.16.4-3.1.0-15.jar"
hash-format = "murmur2"
hash = "2826249651"

[update]
[update.curseforge]
file-id = 3184485
project-id = 224791
release-channel = "beta"
