name = "Bookshelf"
filename = "Bookshelf-1.16.4-9.3.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3133/712/Bookshelf-1.16.4-9.3.18.jar"
hash-format = "murmur2"
hash = "228959538"

[update]
[update.curseforge]
file-id = 3133712
project-id = 228525
release-channel = "beta"
