name = "Bookshelf"
filename = "Bookshelf-1.16.4-9.3.24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3165/13/Bookshelf-1.16.4-9.3.24.jar"
hash-format = "murmur2"
hash = "1374201437"

[update]
[update.curseforge]
file-id = 3165013
project-id = 228525
release-channel = "beta"
