name = "Building Gadgets"
filename = "buildinggadgets-1.16.4-3.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3144/138/buildinggadgets-1.16.4-3.7.3.jar"
hash-format = "murmur2"
hash = "3297554583"

[update]
[update.curseforge]
file-id = 3144138
project-id = 298187
release-channel = "beta"
