name = "Building Gadgets"
filename = "buildinggadgets-3.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3097/299/buildinggadgets-3.7.2.jar"
hash-format = "murmur2"
hash = "2096293239"

[update]
[update.curseforge]
file-id = 3097299
project-id = 298187
release-channel = "beta"
