name = "Caelus API (Forge)"
filename = "caelus-forge-1.16.5-2.1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3224/510/caelus-forge-1.16.5-2.1.3.0.jar"
hash-format = "murmur2"
hash = "1392094778"

[update]
[update.curseforge]
file-id = 3224510
project-id = 308989
release-channel = "beta"
