name = "Carry On"
filename = "carryon-1.16.5-1.15.3.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3206/755/carryon-1.16.5-1.15.3.13.jar"
hash-format = "murmur2"
hash = "1429864299"

[update]
[update.curseforge]
file-id = 3206755
project-id = 274259
release-channel = "beta"
