name = "Champions"
filename = "champions-forge-1.16.5-2.0.1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3243/441/champions-forge-1.16.5-2.0.1.5.jar"
hash-format = "murmur2"
hash = "2225352495"

[update]
[update.curseforge]
file-id = 3243441
project-id = 307152
release-channel = "beta"
