name = "Chisels & Bits"
filename = "chiselsandbits-0.2.8-RELEASE.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3133/859/chiselsandbits-0.2.8-RELEASE.jar"
hash-format = "murmur2"
hash = "4063972124"

[update]
[update.curseforge]
file-id = 3133859
project-id = 231095
release-channel = "beta"
