name = "Client Tweaks"
filename = "ClientTweaks_1.16.3-5.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3066/63/ClientTweaks_1.16.3-5.2.0.jar"
hash-format = "murmur2"
hash = "1764350282"

[update]
[update.curseforge]
file-id = 3066063
project-id = 251407
release-channel = "beta"
