name = "Cloth Config API (Forge)"
filename = "cloth-config-forge-4.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3155/284/cloth-config-forge-4.1.3.jar"
hash-format = "murmur2"
hash = "3298308285"

[update]
[update.curseforge]
file-id = 3155284
project-id = 348521
release-channel = "beta"
