name = "Clumps"
filename = "Clumps-6.0.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3137/103/Clumps-6.0.0.13.jar"
hash-format = "murmur2"
hash = "303149247"

[update]
[update.curseforge]
file-id = 3137103
project-id = 256717
release-channel = "beta"
