name = "CodeChicken Lib 1.8.+"
filename = "CodeChickenLib-1.16.4-3.5.1.408-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3175/750/CodeChickenLib-1.16.4-3.5.1.408-universal.jar"
hash-format = "murmur2"
hash = "3519366091"

[update]
[update.curseforge]
file-id = 3175750
project-id = 242818
release-channel = "beta"
