name = "Comforts (Forge)"
filename = "comforts-forge-1.16.4-4.0.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3156/807/comforts-forge-1.16.4-4.0.1.0.jar"
hash-format = "murmur2"
hash = "2889952409"

[update]
[update.curseforge]
file-id = 3156807
project-id = 276951
release-channel = "beta"
