name = "Compressium"
filename = "Compressium-1.16.4-1.1.36.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3105/279/Compressium-1.16.4-1.1.36.jar"
hash-format = "murmur2"
hash = "2043245026"

[update]
[update.curseforge]
file-id = 3105279
project-id = 342929
release-channel = "beta"
