name = "Controlling"
filename = "Controlling-7.0.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3110/995/Controlling-7.0.0.11.jar"
hash-format = "murmur2"
hash = "2744435979"

[update]
[update.curseforge]
file-id = 3110995
project-id = 250398
release-channel = "beta"
