name = "Crafting Tweaks"
filename = "CraftingTweaks_1.16.3-12.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3066/33/CraftingTweaks_1.16.3-12.2.0.jar"
hash-format = "murmur2"
hash = "1894828785"

[update]
[update.curseforge]
file-id = 3066033
project-id = 233071
release-channel = "beta"
