name = "CraftPresence"
filename = "CraftPresence-Forge-1.16.5-Release-1.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3281/948/CraftPresence-Forge-1.16.5-Release-1.8.1.jar"
hash-format = "murmur2"
hash = "3975268860"

[update]
[update.curseforge]
file-id = 3281948
project-id = 297038
release-channel = "beta"
