name = "Crash Utilities"
filename = "crashutilities-3.8.1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3144/322/crashutilities-3.8.1.jar"
hash-format = "murmur2"
hash = "269798695"

[update]
[update.curseforge]
file-id = 3144322
project-id = 371813
release-channel = "beta"
