name = "Create"
filename = "create-mc1.16.3_v0.3b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3146/74/create-mc1.16.3_v0.3b.jar"
hash-format = "murmur2"
hash = "3450065096"

[update]
[update.curseforge]
file-id = 3146074
project-id = 328085
release-channel = "beta"
