name = "Create"
filename = "create-mc1.16.3_v0.3c.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3158/185/create-mc1.16.3_v0.3c.jar"
hash-format = "murmur2"
hash = "516884127"

[update]
[update.curseforge]
file-id = 3158185
project-id = 328085
release-channel = "beta"
