name = "Culinary Construct"
filename = "culinaryconstruct-forge-1.16.5-4.0.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3217/589/culinaryconstruct-forge-1.16.5-4.0.0.6.jar"
hash-format = "murmur2"
hash = "1596574562"

[update]
[update.curseforge]
file-id = 3217589
project-id = 296676
release-channel = "beta"
