name = "Dank Storage"
filename = "dankstorage-3.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3161/863/dankstorage-3.14.jar"
hash-format = "murmur2"
hash = "3786134363"

[update]
[update.curseforge]
file-id = 3161863
project-id = 335673
release-channel = "beta"
