name = "Discord Integration"
filename = "dcintegration-forge-2.1.1-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3258/592/dcintegration-forge-2.1.1-1.16.jar"
hash-format = "murmur2"
hash = "305229086"

[update]
[update.curseforge]
file-id = 3258592
project-id = 324952
release-channel = "beta"
