name = "Dungeons Plus"
filename = "dungeons_plus-1.16.5-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3261/542/dungeons_plus-1.16.5-1.1.4.jar"
hash-format = "murmur2"
hash = "2916707808"

[update]
[update.curseforge]
file-id = 3261542
project-id = 377794
release-channel = "beta"
