name = "Dungeons Mod"
filename = "DungeonsMod-1.16.3-1.3.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3280/686/DungeonsMod-1.16.3-1.3.13.jar"
hash-format = "murmur2"
hash = "2095512376"

[update]
[update.curseforge]
file-id = 3280686
project-id = 359619
release-channel = "beta"
