name = "Dynamic View"
filename = "dynviewdist-1.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3217/166/dynviewdist-1.9.jar"
hash-format = "murmur2"
hash = "3339318318"

[update]
[update.curseforge]
file-id = 3217166
project-id = 366140
release-channel = "beta"
