name = "Emojiful"
filename = "emojiful-1.16.4-2.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3156/116/emojiful-1.16.4-2.1.2.jar"
hash-format = "murmur2"
hash = "1247612594"

[update]
[update.curseforge]
file-id = 3156116
project-id = 284324
release-channel = "beta"
