name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-fabric-1.16.4-1.0.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3161/609/EnchantmentDescriptions-fabric-1.16.4-1.0.0.jar"
hash-format = "murmur2"
hash = "200062154"

[update]
[update.curseforge]
file-id = 3161609
project-id = 250419
release-channel = "beta"
