name = "EnderChests"
filename = "enderchests-1.16-1.7.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3106/960/enderchests-1.16-1.7.5.jar"
hash-format = "murmur2"
hash = "1833569564"

[update]
[update.curseforge]
file-id = 3106960
project-id = 363535
release-channel = "beta"
