name = "Environmental Core"
filename = "envirocore-1.16.4-3.0.6.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3154/953/envirocore-1.16.4-3.0.6.0.jar"
hash-format = "murmur2"
hash = "3307005065"

[update]
[update.curseforge]
file-id = 3154953
project-id = 345795
release-channel = "beta"
