name = "Environmental Tech"
filename = "envirotech-1.16.4-3.0.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3142/867/envirotech-1.16.4-3.0.5.1.jar"
hash-format = "murmur2"
hash = "3456347759"

[update]
[update.curseforge]
file-id = 3142867
project-id = 245453
release-channel = "beta"
