name = "Fairy Lights"
filename = "fairylights-4.0.4-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3148/608/fairylights-4.0.4-1.16.4.jar"
hash-format = "murmur2"
hash = "4204532921"

[update]
[update.curseforge]
file-id = 3148608
project-id = 233342
release-channel = "beta"
