name = "FindMe"
filename = "findme-1.16.3-2.1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3073/336/findme-1.16.3-2.1.0.0.jar"
hash-format = "murmur2"
hash = "344248038"

[update]
[update.curseforge]
file-id = 3073336
project-id = 291936
release-channel = "beta"
