name = "Flux Networks"
filename = "FluxNetworks-1.16.4-6.1.5.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3111/237/FluxNetworks-1.16.4-6.1.5.10.jar"
hash-format = "murmur2"
hash = "3376684261"

[update]
[update.curseforge]
file-id = 3111237
project-id = 248020
release-channel = "beta"
