name = "ForgeEndertech"
filename = "ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3246/245/ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar"
hash-format = "murmur2"
hash = "702328308"

[update]
[update.curseforge]
file-id = 3246245
project-id = 244844
release-channel = "beta"
