name = "ForgeEndertech"
filename = "ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3161/169/ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar"
hash-format = "murmur2"
hash = "889498631"

[update]
[update.curseforge]
file-id = 3161169
project-id = 244844
release-channel = "beta"
