name = "FTB Teams"
filename = "ftb-teams-1604.1.0.16-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3237/174/ftb-teams-1604.1.0.16-forge.jar"
hash-format = "murmur2"
hash = "2961726476"

[update]
[update.curseforge]
file-id = 3237174
project-id = 404468
release-channel = "beta"
