name = "FTB Ultimine"
filename = "ftb-ultimine-1605.2.0-build.26-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3269/868/ftb-ultimine-1605.2.0-build.26-forge.jar"
hash-format = "murmur2"
hash = "968780460"

[update]
[update.curseforge]
file-id = 3269868
project-id = 386134
release-channel = "beta"
