name = "FTB GUI Library"
filename = "ftb-gui-library-1604.1.1.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3133/0/ftb-gui-library-1604.1.1.26.jar"
hash-format = "murmur2"
hash = "2215478469"

[update]
[update.curseforge]
file-id = 3133000
project-id = 404465
release-channel = "beta"
