name = "FTB Essentials"
filename = "ftb-essentials-1604.1.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3170/610/ftb-essentials-1604.1.0.13.jar"
hash-format = "murmur2"
hash = "3627275976"

[update]
[update.curseforge]
file-id = 3170610
project-id = 410811
release-channel = "beta"
