name = "FTB Ranks"
filename = "ftb-ranks-1604.1.1.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3107/265/ftb-ranks-1604.1.1.9.jar"
hash-format = "murmur2"
hash = "3022613471"

[update]
[update.curseforge]
file-id = 3107265
project-id = 314905
release-channel = "beta"
