name = "FTB Quests"
filename = "ftb-quests-1605.2.1-build.39-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3249/257/ftb-quests-1605.2.1-build.39-forge.jar"
hash-format = "murmur2"
hash = "3843819971"

[update]
[update.curseforge]
file-id = 3249257
project-id = 289412
release-channel = "beta"
