name = "FTB Chunks"
filename = "ftb-chunks-1604.2.2.53.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3142/622/ftb-chunks-1604.2.2.53.jar"
hash-format = "murmur2"
hash = "1223518922"

[update]
[update.curseforge]
file-id = 3142622
project-id = 314906
release-channel = "beta"
