name = "GeckoLib"
filename = "forge-1.16.4-geckolib-3.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3135/745/forge-1.16.4-geckolib-3.0.0.jar"
hash-format = "murmur2"
hash = "2369550246"

[update]
[update.curseforge]
file-id = 3135745
project-id = 388172
release-channel = "beta"
