name = "Hardcore Revival"
filename = "HardcoreRevival_1.16.3-5.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3066/98/HardcoreRevival_1.16.3-5.2.0.jar"
hash-format = "murmur2"
hash = "3131307672"

[update]
[update.curseforge]
file-id = 3066098
project-id = 274036
release-channel = "beta"
