name = "Ice and Fire: Dragons"
filename = "iceandfire-2.1.6-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3217/622/iceandfire-2.1.6-1.16.4.jar"
hash-format = "murmur2"
hash = "1924019527"

[update]
[update.curseforge]
file-id = 3217622
project-id = 264231
release-channel = "beta"
