name = "Ice and Fire: Dragons"
filename = "iceandfire-2.1.5-1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3162/719/iceandfire-2.1.5-1.16.4.jar"
hash-format = "murmur2"
hash = "3318151318"

[update]
[update.curseforge]
file-id = 3162719
project-id = 264231
release-channel = "beta"
