name = "Industrial Foregoing"
filename = "industrial-foregoing-1.16.4-3.2.6-c3ea663.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3143/186/industrial-foregoing-1.16.4-3.2.6-c3ea663.jar"
hash-format = "murmur2"
hash = "494354570"

[update]
[update.curseforge]
file-id = 3143186
project-id = 266515
release-channel = "beta"
