name = "Integrated Tunnels"
filename = "IntegratedTunnels-1.16.5-1.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3256/914/IntegratedTunnels-1.16.5-1.7.1.jar"
hash-format = "murmur2"
hash = "3454536896"

[update]
[update.curseforge]
file-id = 3256914
project-id = 251389
release-channel = "beta"
