name = "JAOPCA"
filename = "JAOPCA-1.16.4-3.4.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3148/139/JAOPCA-1.16.4-3.4.0.2.jar"
hash-format = "murmur2"
hash = "3133322715"

[update]
[update.curseforge]
file-id = 3148139
project-id = 266936
release-channel = "beta"
