name = "Just Enough Items (JEI)"
filename = "jei-1.16.4-7.6.1.65.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3157/864/jei-1.16.4-7.6.1.65.jar"
hash-format = "murmur2"
hash = "3072337373"

[update]
[update.curseforge]
file-id = 3157864
project-id = 238222
release-channel = "beta"
