name = "Just Enough Resources (JER)"
filename = "JustEnoughResources-1.16.4-0.12.0.103.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3109/962/JustEnoughResources-1.16.4-0.12.0.103.jar"
hash-format = "murmur2"
hash = "3141810659"

[update]
[update.curseforge]
file-id = 3109962
project-id = 240630
release-channel = "beta"
