name = "Just Enough Resources (JER)"
filename = "JustEnoughResources-1.16.4-0.12.0.104.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3166/519/JustEnoughResources-1.16.4-0.12.0.104.jar"
hash-format = "murmur2"
hash = "89227628"

[update]
[update.curseforge]
file-id = 3166519
project-id = 240630
release-channel = "beta"
