name = "🥝 Kiwi"
filename = "Kiwi-1.16.3-3.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3103/509/Kiwi-1.16.3-3.4.1.jar"
hash-format = "murmur2"
hash = "2893812894"

[update]
[update.curseforge]
file-id = 3103509
project-id = 303657
release-channel = "beta"
