name = "KleeSlabs"
filename = "KleeSlabs_1.16.3-9.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3066/71/KleeSlabs_1.16.3-9.2.0.jar"
hash-format = "murmur2"
hash = "2901737293"

[update]
[update.curseforge]
file-id = 3066071
project-id = 241895
release-channel = "beta"
