name = "KubeJS"
filename = "kubejs-1604.3.4.143-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3164/143/kubejs-1604.3.4.143-forge.jar"
hash-format = "murmur2"
hash = "1233381969"

[update]
[update.curseforge]
file-id = 3164143
project-id = 238086
release-channel = "beta"
