name = "KubeJS Mekanism"
filename = "kubejs-mekanism-1604.1.1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3159/438/kubejs-mekanism-1604.1.1.6.jar"
hash-format = "murmur2"
hash = "994757549"

[update]
[update.curseforge]
file-id = 3159438
project-id = 418651
release-channel = "beta"
