name = "KubeJS"
filename = "kubejs-1604.3.2.123-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3146/42/kubejs-1604.3.2.123-forge.jar"
hash-format = "murmur2"
hash = "3846915779"

[update]
[update.curseforge]
file-id = 3146042
project-id = 238086
release-channel = "beta"
