name = "KubeJS"
filename = "kubejs-1605.3.7-build.186-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3286/650/kubejs-1605.3.7-build.186-forge.jar"
hash-format = "murmur2"
hash = "2729659415"

[update]
[update.curseforge]
file-id = 3286650
project-id = 238086
release-channel = "beta"
