name = "KubeJS"
filename = "kubejs-1604.3.2.122-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3145/494/kubejs-1604.3.2.122-forge.jar"
hash-format = "murmur2"
hash = "4236429314"

[update]
[update.curseforge]
file-id = 3145494
project-id = 238086
release-channel = "beta"
