name = "Lighting Wand 🌟"
filename = "LightingWand-1.16.4-1.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3162/246/LightingWand-1.16.4-1.7.3.jar"
hash-format = "murmur2"
hash = "3078981677"

[update]
[update.curseforge]
file-id = 3162246
project-id = 296028
release-channel = "beta"
