name = "Macaw's Roofs"
filename = "mcws-roofs-2.0.0-mc1.16.4.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3100/991/mcws-roofs-2.0.0-mc1.16.4.jar"
hash-format = "murmur2"
hash = "1867663839"

[update]
[update.curseforge]
file-id = 3100991
project-id = 352039
release-channel = "beta"
