name = "Macaw's Doors"
filename = "mcw-doors-1.0.1fix-mc1.16.4.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3100/990/mcw-doors-1.0.1fix-mc1.16.4.jar"
hash-format = "murmur2"
hash = "1570733451"

[update]
[update.curseforge]
file-id = 3100990
project-id = 378646
release-channel = "beta"
