name = "Macaw's Bridges"
filename = "mcw-bridges-1.0.5-mc1.16.5-4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3182/346/mcw-bridges-1.0.5-mc1.16.5-4.jar"
hash-format = "murmur2"
hash = "2358995780"

[update]
[update.curseforge]
file-id = 3182346
project-id = 351725
release-channel = "beta"
