name = "Mahou Tsukai"
filename = "mahoutsukai-1.16.5-v1.30.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3289/318/mahoutsukai-1.16.5-v1.30.0.jar"
hash-format = "murmur2"
hash = "2079034897"

[update]
[update.curseforge]
file-id = 3289318
project-id = 342543
release-channel = "beta"
