name = "McJtyLib"
filename = "mcjtylib-1.16-5.0.15.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3131/241/mcjtylib-1.16-5.0.15.jar"
hash-format = "murmur2"
hash = "3282298992"

[update]
[update.curseforge]
file-id = 3131241
project-id = 233105
release-channel = "beta"
