name = "MCMT"
filename = "jmt_mcmt-1.16.5-0.20.75.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3274/365/jmt_mcmt-1.16.5-0.20.75.jar"
hash-format = "murmur2"
hash = "2866238802"

[update]
[update.curseforge]
file-id = 3274365
project-id = 401447
release-channel = "beta"
