name = "Mekanism"
filename = "Mekanism-1.16.4-10.0.18.445.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3134/211/Mekanism-1.16.4-10.0.18.445.jar"
hash-format = "murmur2"
hash = "3710360477"

[update]
[update.curseforge]
file-id = 3134211
project-id = 268560
release-channel = "beta"
