name = "mGui"
filename = "mgui-1.16.4-3.1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3104/239/mgui-1.16.4-3.1.3.jar"
hash-format = "murmur2"
hash = "317542755"

[update]
[update.curseforge]
file-id = 3104239
project-id = 351914
release-channel = "beta"
