name = "MineColonies"
filename = "minecolonies-0.14.123-ALPHA-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3288/708/minecolonies-0.14.123-ALPHA-universal.jar"
hash-format = "murmur2"
hash = "1827875222"

[update]
[update.curseforge]
file-id = 3288708
project-id = 245506
release-channel = "beta"
