name = "Mouse Tweaks"
filename = "MouseTweaks-2.13-mc1.16.2.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3035/780/MouseTweaks-2.13-mc1.16.2.jar"
hash-format = "murmur2"
hash = "2437852686"

[update]
[update.curseforge]
file-id = 3035780
project-id = 60089
release-channel = "beta"
