name = "MrCrayfish's Furniture Mod"
filename = "furniture-7.0.0-pre19-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3081/350/furniture-7.0.0-pre19-1.16.3.jar"
hash-format = "murmur2"
hash = "4106451381"

[update]
[update.curseforge]
file-id = 3081350
project-id = 55438
release-channel = "beta"
