name = "OptiForge"
filename = "OptiForge-MC1.16.4-0.4.6.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3165/83/OptiForge-MC1.16.4-0.4.6.jar"
hash-format = "murmur2"
hash = "70486177"

[update]
[update.curseforge]
file-id = 3165083
project-id = 372196
release-channel = "beta"
