name = "OptiForge"
filename = "OptiForge-MC1.16.4-0.4.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3120/749/OptiForge-MC1.16.4-0.4.3.jar"
hash-format = "murmur2"
hash = "3747891160"

[update]
[update.curseforge]
file-id = 3120749
project-id = 372196
release-channel = "beta"
