name = "Pane In The Glass"
filename = "pitg-1.16.3-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3251/859/pitg-1.16.3-1.4.2.jar"
hash-format = "murmur2"
hash = "2524949862"

[update]
[update.curseforge]
file-id = 3251859
project-id = 374529
release-channel = "beta"
