name = "Pickle Tweaks"
filename = "PickleTweaks-1.16.4-5.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3101/695/PickleTweaks-1.16.4-5.1.4.jar"
hash-format = "murmur2"
hash = "329615743"

[update]
[update.curseforge]
file-id = 3101695
project-id = 238761
release-channel = "beta"
