name = "PneumaticCraft: Repressurized"
filename = "pneumaticcraft-repressurized-1.16.4-2.9.1-115.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3165/179/pneumaticcraft-repressurized-1.16.4-2.9.1-115.jar"
hash-format = "murmur2"
hash = "3702862185"

[update]
[update.curseforge]
file-id = 3165179
project-id = 281849
release-channel = "beta"
