name = "Polymorph (Forge)"
filename = "polymorph-forge-1.16.4-0.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3143/900/polymorph-forge-1.16.4-0.20.jar"
hash-format = "murmur2"
hash = "2207553170"

[update]
[update.curseforge]
file-id = 3143900
project-id = 388800
release-channel = "beta"
