name = "Portality"
filename = "portality-1.16.4-3.2.0.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3101/153/portality-1.16.4-3.2.0.jar"
hash-format = "murmur2"
hash = "1262199177"

[update]
[update.curseforge]
file-id = 3101153
project-id = 291493
release-channel = "beta"
