name = "Prefab"
filename = "prefab-1.6.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3160/190/prefab-1.6.4.2.jar"
hash-format = "murmur2"
hash = "3730371403"

[update]
[update.curseforge]
file-id = 3160190
project-id = 246550
release-channel = "beta"
