name = "Psi"
filename = "Psi 1.16-94.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3288/535/Psi 1.16-94.jar"
hash-format = "murmur2"
hash = "947812386"

[update]
[update.curseforge]
file-id = 3288535
project-id = 241665
release-channel = "beta"
