name = "Psi"
filename = "Psi 1.16-93.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3258/606/Psi 1.16-93.jar"
hash-format = "murmur2"
hash = "3213090732"

[update]
[update.curseforge]
file-id = 3258606
project-id = 241665
release-channel = "beta"
