name = "Quark"
filename = "Quark-r2.4-281.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3144/658/Quark-r2.4-281.jar"
hash-format = "murmur2"
hash = "3982328958"

[update]
[update.curseforge]
file-id = 3144658
project-id = 243121
release-channel = "beta"
