name = "Quark"
filename = "Quark-r2.4-311.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3282/239/Quark-r2.4-311.jar"
hash-format = "murmur2"
hash = "2592516764"

[update]
[update.curseforge]
file-id = 3282239
project-id = 243121
release-channel = "beta"
