name = "Quark"
filename = "Quark-r2.4-293.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3166/273/Quark-r2.4-293.jar"
hash-format = "murmur2"
hash = "3656302341"

[update]
[update.curseforge]
file-id = 3166273
project-id = 243121
release-channel = "beta"
