name = "Ranged Pumps"
filename = "rangedpumps-0.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3065/697/rangedpumps-0.8.2.jar"
hash-format = "murmur2"
hash = "870328279"

[update]
[update.curseforge]
file-id = 3065697
project-id = 247496
release-channel = "beta"
