name = "Gauges and Switches"
filename = "rsgauges-1.16.4-1.2.7-b2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3164/258/rsgauges-1.16.4-1.2.7-b2.jar"
hash-format = "murmur2"
hash = "748308264"

[update]
[update.curseforge]
file-id = 3164258
project-id = 296686
release-channel = "beta"
