name = "Gauges and Switches"
filename = "rsgauges-1.16.4-1.2.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3287/295/rsgauges-1.16.4-1.2.9.jar"
hash-format = "murmur2"
hash = "2587703849"

[update]
[update.curseforge]
file-id = 3287295
project-id = 296686
release-channel = "beta"
