name = "Reload Audio Driver (RAD) [Forge]"
filename = "rad-1.16-4.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3054/516/rad-1.16-4.1.0.jar"
hash-format = "murmur2"
hash = "2180814080"

[update]
[update.curseforge]
file-id = 3054516
project-id = 305373
release-channel = "beta"
