name = "Restrictions"
filename = "restrictions-1.16-3.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3057/538/restrictions-1.16-3.0.3.jar"
hash-format = "murmur2"
hash = "639551013"

[update]
[update.curseforge]
file-id = 3057538
project-id = 282805
release-channel = "beta"
