name = "RFTools Utility"
filename = "rftoolsutility-1.16-3.0.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3152/948/rftoolsutility-1.16-3.0.20.jar"
hash-format = "murmur2"
hash = "3256695014"

[update]
[update.curseforge]
file-id = 3152948
project-id = 342466
release-channel = "beta"
