name = "RFTools Power"
filename = "rftoolspower-1.16-3.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3087/309/rftoolspower-1.16-3.0.8.jar"
hash-format = "murmur2"
hash = "4056153139"

[update]
[update.curseforge]
file-id = 3087309
project-id = 290209
release-channel = "beta"
