name = "RFTools Builder"
filename = "rftoolsbuilder-1.16-3.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3140/151/rftoolsbuilder-1.16-3.0.13.jar"
hash-format = "murmur2"
hash = "3532595591"

[update]
[update.curseforge]
file-id = 3140151
project-id = 347706
release-channel = "beta"
