name = "RFTools Control"
filename = "rftoolscontrol-1.16-4.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3096/835/rftoolscontrol-1.16-4.0.6.jar"
hash-format = "murmur2"
hash = "1015370444"

[update]
[update.curseforge]
file-id = 3096835
project-id = 250763
release-channel = "beta"
