name = "RFTools Base"
filename = "rftoolsbase-1.16-2.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3140/147/rftoolsbase-1.16-2.0.9.jar"
hash-format = "murmur2"
hash = "2872062914"

[update]
[update.curseforge]
file-id = 3140147
project-id = 326041
release-channel = "beta"
