name = "Rhino"
filename = "rhino-1.7.13-build.23.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3279/704/rhino-1.7.13-build.23.jar"
hash-format = "murmur2"
hash = "149318497"

[update]
[update.curseforge]
file-id = 3279704
project-id = 416294
release-channel = "beta"
