name = "Rhino"
filename = "rhino-1.7.13.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3162/251/rhino-1.7.13.10.jar"
hash-format = "murmur2"
hash = "2786381863"

[update]
[update.curseforge]
file-id = 3162251
project-id = 416294
release-channel = "beta"
