name = "Rhino"
filename = "rhino-1.7.13.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3124/36/rhino-1.7.13.9.jar"
hash-format = "murmur2"
hash = "2470810748"

[update]
[update.curseforge]
file-id = 3124036
project-id = 416294
release-channel = "beta"
