name = "ShetiPhianCore"
filename = "shetiphiancore-1.16-3.8.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3203/264/shetiphiancore-1.16-3.8.5.jar"
hash-format = "murmur2"
hash = "3442156077"

[update]
[update.curseforge]
file-id = 3203264
project-id = 71738
release-channel = "beta"
