name = "Shutup Experimental Settings!"
filename = "shutupexperimentalsettings-1.0.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3090/291/shutupexperimentalsettings-1.0.1.jar"
hash-format = "murmur2"
hash = "3818939662"

[update]
[update.curseforge]
file-id = 3090291
project-id = 407174
release-channel = "beta"
