name = "Simply Light"
filename = "simplylight-1.16.4-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3118/974/simplylight-1.16.4-1.1.1.jar"
hash-format = "murmur2"
hash = "2802391546"

[update]
[update.curseforge]
file-id = 3118974
project-id = 300331
release-channel = "beta"
