name = "☃ Snow! Real Magic!"
filename = "SnowRealMagic-1.16.3-2.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3125/223/SnowRealMagic-1.16.3-2.2.2.jar"
hash-format = "murmur2"
hash = "3792073933"

[update]
[update.curseforge]
file-id = 3125223
project-id = 308663
release-channel = "beta"
