name = "Snow! Real Magic! ⛄"
filename = "SnowRealMagic-1.16.4-2.5.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3275/696/SnowRealMagic-1.16.4-2.5.5.jar"
hash-format = "murmur2"
hash = "3953842702"

[update]
[update.curseforge]
file-id = 3275696
project-id = 308663
release-channel = "beta"
