name = "Spartan Shields"
filename = "SpartanShields-1.16.4-2.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3168/405/SpartanShields-1.16.4-2.1.1.jar"
hash-format = "murmur2"
hash = "2902465073"

[update]
[update.curseforge]
file-id = 3168405
project-id = 252239
release-channel = "beta"
