name = "Storage Drawers"
filename = "StorageDrawers-1.16.3-8.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3092/987/StorageDrawers-1.16.3-8.2.1.jar"
hash-format = "murmur2"
hash = "2361489989"

[update]
[update.curseforge]
file-id = 3092987
project-id = 223852
release-channel = "beta"
