name = "Storage Drawers"
filename = "StorageDrawers-1.16.3-8.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3180/569/StorageDrawers-1.16.3-8.2.2.jar"
hash-format = "murmur2"
hash = "883976394"

[update]
[update.curseforge]
file-id = 3180569
project-id = 223852
release-channel = "beta"
