name = "Structurize"
filename = "structurize-0.13.167-ALPHA-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3288/519/structurize-0.13.167-ALPHA-universal.jar"
hash-format = "murmur2"
hash = "2849695036"

[update]
[update.curseforge]
file-id = 3288519
project-id = 298744
release-channel = "beta"
