name = "Structure Gel API"
filename = "structure-gel-api-1.16.4-1.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3133/625/structure-gel-api-1.16.4-1.7.2.jar"
hash-format = "murmur2"
hash = "2078468792"

[update]
[update.curseforge]
file-id = 3133625
project-id = 378802
release-channel = "beta"
