name = "Structure Gel API"
filename = "structure_gel-1.16.4-1.7.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3164/696/structure_gel-1.16.4-1.7.3.jar"
hash-format = "murmur2"
hash = "2450010404"

[update]
[update.curseforge]
file-id = 3164696
project-id = 378802
release-channel = "beta"
