name = "TerraForged"
filename = "TerraForged-1.16.4-0.2.0-ALPHA-4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3144/548/TerraForged-1.16.4-0.2.0-ALPHA-4.jar"
hash-format = "murmur2"
hash = "3174972734"

[update]
[update.curseforge]
file-id = 3144548
project-id = 363820
release-channel = "beta"
