name = "TerraForged"
filename = "TerraForged-1.16.4-0.2.0-ALPHA-2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3143/251/TerraForged-1.16.4-0.2.0-ALPHA-2.jar"
hash-format = "murmur2"
hash = "230846872"

[update]
[update.curseforge]
file-id = 3143251
project-id = 363820
release-channel = "beta"
