name = "Tetra"
filename = "tetra-1.16.5-3.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3232/294/tetra-1.16.5-3.8.0.jar"
hash-format = "murmur2"
hash = "305738952"

[update]
[update.curseforge]
file-id = 3232294
project-id = 289712
release-channel = "beta"
