name = "The One Probe"
filename = "theoneprobe-1.16-3.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3157/997/theoneprobe-1.16-3.0.7.jar"
hash-format = "murmur2"
hash = "1240636736"

[update]
[update.curseforge]
file-id = 3157997
project-id = 245211
release-channel = "beta"
