name = "The Mighty Architect"
filename = "mightyarchitect-mc1.16.3_v0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3089/690/mightyarchitect-mc1.16.3_v0.5.jar"
hash-format = "murmur2"
hash = "1913767755"

[update]
[update.curseforge]
file-id = 3089690
project-id = 317792
release-channel = "beta"
