name = "Thermal Expansion"
filename = "thermal_expansion-1.16.3-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3104/355/thermal_expansion-1.16.3-1.0.5.jar"
hash-format = "murmur2"
hash = "2385430414"

[update]
[update.curseforge]
file-id = 3104355
project-id = 69163
release-channel = "beta"
