name = "Thermal Foundation"
filename = "thermal-1.16.3-1.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3104/383/thermal-1.16.3-1.0.5.jar"
hash-format = "murmur2"
hash = "1552161055"

[update]
[update.curseforge]
file-id = 3104383
project-id = 222880
release-channel = "beta"
