name = "Thermal Locomotion"
filename = "thermal_locomotion-1.16.3-1.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3101/646/thermal_locomotion-1.16.3-1.0.3.jar"
hash-format = "murmur2"
hash = "3589915376"

[update]
[update.curseforge]
file-id = 3101646
project-id = 406959
release-channel = "beta"
