name = "Titanium"
filename = "titanium-1.16.5-3.2.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3261/72/titanium-1.16.5-3.2.8.2.jar"
hash-format = "murmur2"
hash = "359589884"

[update]
[update.curseforge]
file-id = 3261072
project-id = 287342
release-channel = "beta"
