name = "Titanium"
filename = "titanium-1.16.4-3.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3163/247/titanium-1.16.4-3.2.5.jar"
hash-format = "murmur2"
hash = "3993692416"

[update]
[update.curseforge]
file-id = 3163247
project-id = 287342
release-channel = "beta"
