name = "Tool Belt"
filename = "ToolBelt-1.16.3-1.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3086/49/ToolBelt-1.16.3-1.15.2.jar"
hash-format = "murmur2"
hash = "1755831488"

[update]
[update.curseforge]
file-id = 3086049
project-id = 260262
release-channel = "beta"
