name = "Trash Cans"
filename = "trashcans-1.0.6-mc1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3156/205/trashcans-1.0.6-mc1.16.4.jar"
hash-format = "murmur2"
hash = "2917370955"

[update]
[update.curseforge]
file-id = 3156205
project-id = 394535
release-channel = "beta"
