name = "Trash Cans"
filename = "trashcans-1.0.9-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3278/995/trashcans-1.0.9-mc1.16.5.jar"
hash-format = "murmur2"
hash = "2398728556"

[update]
[update.curseforge]
file-id = 3278995
project-id = 394535
release-channel = "beta"
