name = "U Team Core"
filename = "u_team_core-1.16.5-3.2.0.194.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3257/635/u_team_core-1.16.5-3.2.0.194.jar"
hash-format = "murmur2"
hash = "1369955082"

[update]
[update.curseforge]
file-id = 3257635
project-id = 273744
release-channel = "beta"
