name = "Useful Backpacks"
filename = "useful_backpacks-1.16.4-1.11.6.86.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3106/326/useful_backpacks-1.16.4-1.11.6.86.jar"
hash-format = "murmur2"
hash = "3701637437"

[update]
[update.curseforge]
file-id = 3106326
project-id = 274338
release-channel = "beta"
