name = "ValkyrieLib"
filename = "valkyrielib-1.16.4-3.0.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3154/961/valkyrielib-1.16.4-3.0.6.1.jar"
hash-format = "murmur2"
hash = "3419093508"

[update]
[update.curseforge]
file-id = 3154961
project-id = 245480
release-channel = "beta"
