name = "Vivecraft Forge Extensions"
filename = "VivecraftForgeExtensions-1.16.4-1.3.3.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3107/340/VivecraftForgeExtensions-1.16.4-1.3.3.jar"
hash-format = "murmur2"
hash = "400701515"

[update]
[update.curseforge]
file-id = 3107340
project-id = 325360
release-channel = "beta"
