name = "Waystones"
filename = "Waystones_1.16.5-7.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3222/129/Waystones_1.16.5-7.4.0.jar"
hash-format = "murmur2"
hash = "2138849741"

[update]
[update.curseforge]
file-id = 3222129
project-id = 245755
release-channel = "beta"
