name = "Wither Skeleton Tweaks"
filename = "Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3069/856/Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar"
hash-format = "murmur2"
hash = "3814773290"

[update]
[update.curseforge]
file-id = 3069856
project-id = 255902
release-channel = "beta"
