name = "Woot"
filename = "woot-1.16.4-1.0.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3155/205/woot-1.16.4-1.0.3.0.jar"
hash-format = "murmur2"
hash = "2646083882"

[update]
[update.curseforge]
file-id = 3155205
project-id = 244049
release-channel = "beta"
