name = "XNet Gases"
filename = "XNetGases-1.16.4-2.2.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3161/188/XNetGases-1.16.4-2.2.3.jar"
hash-format = "murmur2"
hash = "804869329"

[update]
[update.curseforge]
file-id = 3161188
project-id = 383182
release-channel = "beta"
