name = "YUNG's Better Mineshafts (Forge)"
filename = "BetterMineshafts-Forge-1.16.3-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3145/910/BetterMineshafts-Forge-1.16.3-1.1.1.jar"
hash-format = "murmur2"
hash = "2114281243"

[update]
[update.curseforge]
file-id = 3145910
project-id = 389665
release-channel = "beta"
