name = "YUNG's Better Caves (Forge)"
filename = "BetterCaves-1.16.3-1.0.6.jar"
side = "both"

[download]
url = "https://edge-service.overwolf.wtf/files/3128/132/BetterCaves-1.16.3-1.0.6.jar"
hash-format = "murmur2"
hash = "3123186311"

[update]
[update.curseforge]
file-id = 3128132
project-id = 340583
release-channel = "beta"
