name = "YUNG's Better Caves (Forge)"
filename = "BetterCaves-Forge-1.16.4-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3170/47/BetterCaves-Forge-1.16.4-1.1.1.jar"
hash-format = "murmur2"
hash = "1900831172"

[update]
[update.curseforge]
file-id = 3170047
project-id = 340583
release-channel = "beta"
